# 02 NumPy Basics

- sort()
- random()

In [1]:
import numpy as np

In [2]:
#use magic command to set the float .3f
%precision 3

'%.3f'

## NumPy 亂數
使用 NumPy 的亂數功能 `random()`，建議先指定「種子」，作為之後驗證資料所用。

In [11]:
#指定種子為0
np.random.seed(0)

data = np.array([9,2,7,19,34,6,39,22,8,6,466])

#隨機取出10個，允許取出重複元素
print(np.random.choice(data, 10))

#隨機取出10個，不允許取出重複元素
print(np.random.choice(data, 10, replace = False))

[ 6  9 19 19 22  6 19  6  7 34]
[  6 466  19   6   2   7  34   9   8  39]


In [15]:
#指定種子為4
np.random.seed(0)

data = np.array([9,2,7,19,34,6,39,22,8,6,466])

#隨機取出10個，允許取出重複元素
print(np.random.choice(data, 20))

#隨機取出10個，不允許取出重複元素
print(np.random.choice(data, 10, replace = False))

[  6   9  19  19  22   6  19   6   7  34  22  39   8   8 466   2  39  22
  22   8]
[  7  39  22   6   9  19  34 466   8   6]


## NumPy 矩陣

1. 使用 `reshpae(行數,列數)` 產生矩陣，需注意的是矩陣乘法為 `dot()`。
2. `np.zeros` 自動產生全為0的矩陣、`np.ones` 自動產生全為1的矩陣。

In [18]:
#先用 arange() 產生array，再以 reshape() 產生矩陣
array1 = np.arange(16).reshape(4,4)
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
array2 = np.arange(16).reshape(4,4)
print(array2)

#兩矩陣相乘
result = np.dot(array1,array2)
print('The result: ', result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The result:  [[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


In [21]:
#矩陣中個元素相乘
print(array1*array2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [23]:
#產生全為0或1的矩陣
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


## Question and Answer

In [26]:
#Q2-1
new_array = np.array([i for i in range(1, 51)])
array_sum = sum(new_array)
print(array_sum)

1275


In [28]:
#Q2-2
np.random.seed(0)
new_matrix = np.random.randn(10).reshape(2, 5)
print('the matrix is: ', new_matrix)
print('the minimum is: ', new_matrix.min())
print('the maximum is: ', new_matrix.max())
print('the sum is: ', new_matrix.sum())

the matrix is:  [[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]]
the minimum is:  -0.977277879876411
the maximum is:  2.240893199201458
the sum is:  7.380231707288347


In [29]:
#Q2-3
three_matrix = np.ones((5, 5), dtype='int') * 3
print(np.dot(three_matrix, three_matrix))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
